hotwired/stimulus-rails

README.md

Stimulus 2.0 has been released, and has a newer
`data-$IDENTIFIER-target` syntax for declaring a Controller's targets.

Update README example to use Stimulus 2 attributes

---

lib/install/stimulus.rb

When trying to deploy the following error happened to me:
```
Errno::ENOENT: No such file or directory @ dir_initialize - /tmp/build_00ed1b07/app/assets/javascripts/libraries
```
It was because the folder was empty thus not committed with Git.
This commit just adds the file, so we always ensure the folder is committed.

Add .keep file to empty directory

---

.github/workflows/ci.yml
Gemfile
Gemfile.lock
app/assets/javascripts/stimulus/loaders/autoloader.js
app/helpers/stimulus/stimulus_helper.rb
lib/stimulus/importmap_helper.rb
test/application_system_test_case.rb
test/dummy/app/assets/config/manifest.js
test/dummy/app/assets/javascripts/controllers/message_rendering_controller.js
test/dummy/app/assets/javascripts/controllers/namespace/message_rendering_controller.js
test/dummy/app/assets/javascripts/importmap.json.erb
test/dummy/app/views/application/index.html.erb
test/dummy/app/views/layouts/application.html.erb
test/dummy/config/routes.rb
test/stimulus_test.rb
test/system/autoload_test.rb

Duplicate of #3
Closes https://github.com/hotwired/stimulus-rails/issues/4
Closes https://github.com/hotwired/stimulus-rails/issues/14
Modifies the `stimulus/loaders/autoloader` module to account for module
importing in 4 different scenarios:
1. Immediately when parsed
2. Whenever elements that declare `[data-controller]` are added,
deleted, or modified (via a [MutationObserver][])
3. Whenever the `DOMContentLoaded` event fires (for applications that
don't depend on `turbo`
4. Whenever the `turbo:load` event fires (for applications that **do**
depend on `turbo`
In addition to autoloading in more scenarios, this commit also changes
the autoloader to read controller tokens in a spacing-agnostic manner,
and to transform [dasherized controller names (like
`message-rendering`)][modules] to …

Make Autoloading more robust

---

.github/workflows/ci.yml
test/stimulus_test.rb

Sets environment variables under the [env][] key to ensure that
`test/{system,dummy}/**/*_test.rb` are not skipped.
To address ordering issues, change the `StimulusTest` to compare the
generated strings as JSON.
[env]: https://docs.github.com/en/actions/reference/environment-variables

Run full suite in CI

---

app/assets/javascripts/stimulus/loaders/autoloader.js
test/dummy/app/assets/javascripts/controllers/loading_controller.js
test/dummy/app/views/application/index.html.erb
test/stimulus_test.rb
test/system/autoload_test.rb

Closes https://github.com/hotwired/stimulus-rails/issues/27
To handle both types of element mutations of interest, [treat
`attributes` mutations different from `childList`
mutations][MutationRecord]. When an `attributes` mutation occurs, load
the added controllers. When a `childList` mutation occurs, load
controllers from any descendant elements.
[MutationRecord]: https://developer.mozilla.org/en-US/docs/Web/API/MutationRecord
Co-authored-by: Justin Malčić <j.malcic@me.com>

Improve Autoloader

---

Gemfile
Gemfile.lock
app/assets/javascripts/stimulus/loaders/autoloader.js
test/dummy/app/views/application/no_controllers.html.erb
test/dummy/app/views/application/turbo.html.erb
test/dummy/app/views/layouts/application.html.erb
test/dummy/config/routes.rb
test/system/autoload_test.rb

Closes https://github.com/hotwired/hotwire-rails/issues/19
---
Instead of attaching the `MutationObserver` to the `document.body`
element, this commit instead attaches it to the `document` itself so
that observation spans Turbo-powered `HTMLBodyElement.innerHTML`
re-assignment.
Add test coverage to reproduce the behavior reported by
[hotwired/hotwire-rails#19][] and ensure that navigating between pages
does not break controller autoloading.
Prior to this commit, navigations triggered via Turbo visits would not
autoload controllers. This commit adds test coverage integrating with
Turbo the `turbo-rails` gem.
[hotwired/hotwire-rails#19]: https://github.com/hotwired/hotwire-rails/issues/19

Attach MutationObserver to `document`

---

app/assets/javascripts/stimulus/controllers/checkbox_list_controller.js

Proposal for a `checkbox-list` controller. No targets, just `checkAll` / `checkNone` actions that set the `checked` value of any non-disabled child checkboxes.
I have a version that binds a `counter` target to check the number of items selected (useful for bulk actions) that I'm happy to share if there is interest, but opted for the simplest version for now.
@dhh 
Examples:
(`Clear filter` unchecks all)
✌️

Add checkbox-list controller

---

lib/install/app/assets/javascripts/controllers/index.js

Hi, this PR comes from #33. 
Now `stimulus:install:webpacker` will lead to an error but `webpacker:install:stimulus` won't.
After comparing the code, I find `stimulus` has missed this setup file to work. This file is taken from  [webpacker](https://github.com/rails/webpacker/blob/v4.0.0/lib/install/examples/stimulus/controllers/index.js).
Thanks for your hard work 😄

add index for webpacker

---

app/assets/javascripts/stimulus/loaders/autoloader.js

Skip if provided an empty string

Use getAttribute to ignore empty controller name

---

lib/stimulus/importmap_helper.rb
test/stimulus_test.rb

There is a small issue in the import map helper when ALL folders exists and have no files to load. It generates a malformed JSON like this one (note the 'extra' comma):
```
{
"imports": {
"stimulus": "/assets/stimulus/libraries/stimulus-dcca1023.js",
}
}
```
using the default `importmap.json.erb`:
```
{
"imports": { 
<%= importmap_list_with_stimulus_from "app/assets/javascripts/controllers", "app/assets/javascripts/libraries" %>
}
}
```
and both folders have no js files to load.
This is because the `[].join` will return an empty string `""` in `importmap_list_from` and later this will become in the extra comma and the malformed JSON. 
I've decided just exclude the empty string, but you're welcome to propose something different.
PS: this case can easily happen when you start a project and …

Fix imports JSON when no files to load

---

Gemfile.lock
lib/stimulus/importmap_helper.rb
lib/stimulus/version.rb
test/stimulus_test.rb

This PR adds support for absolute paths to be included in the `importmap.json` file, as mentioned in #38 . This is especially useful when including stimulus controllers found in a Rails engine. Supports both Pathname and string paths, passed to it.
Example:
```
{
"imports": {
"turbo": "<%= asset_path("turbo") %>",
<%= importmap_list_with_stimulus_from "app/assets/javascripts/controllers", "app/assets/javascripts/libraries", "#{AppKit::Engine.root}/app/assets/javascripts/controllers", "#{AppKit::Engine.root}/app/assets/javascripts/libraries" %>
}
}
```
Thanks!
Bjorn

Support absolute paths (and thereby Rails engines)

---

lib/stimulus/importmap_helper.rb

This method [has been added in Rails 6.1](https://github.com/rails/rails/commit/c8847c17a7c9ae75c44c522c56ccd9c5fca25ea7) and stimulus-rails is also compatible with Rails 6.0, as its [gemspec](https://github.com/hotwired/stimulus-rails/blob/3611362a7179b21c9f28657b7b2085e5bf6f7909/stimulus-rails.gemspec#L17) tells.

Remove compact_blank usage

---

lib/install/app/assets/javascripts/controllers/index.js

I created a Typescript controller and it was showing as successfully compiling in Webpacker logs but Stimulus was just ignoring its existence when I'd reference it with `data-controller` in the DOM. I made the attached change and Stimulus started using it.

Look for Typescript files when loading controllers

---

app/helpers/stimulus/stimulus_helper.rb

This is needed when using the importmap provided by some Engine.
The path of the importmap is probably namespaced under some directories to avoid collisions with other Engines.
A practical example: 
Imagine there's a gem that distributes its own layout file with its own assets. We have this code in its `<head>` tag:
```erb
<head>
<%= stimulus_include_tags("importmap.json") %>
...
</head>
```
The importmap contains something like this (thanks to #39):
```
{
"imports": {
<%= importmap_list_with_stimulus_from(
MyGem::Engine.root.join("app/assets/javascripts/controllers"),
MyGem::Engine.root.join("app/assets/javascripts/libraries"),
) %>
}
}
```
Of course, the importmap is being added to the list of things to precompile in the gem's manifest
```
....
//= link importmap.json
```
This works …

Allow including importmap from custom location

---

README.md
stimulus-rails.gemspec

`https://stimulus.hotwire.dev` → `https://stimulus.hotwired.dev`
As per: hotwired/hotwire-site@22a11ac

Update the Hotwire subdomains

---

lib/install/stimulus_with_webpacker.rb

This PR resolves the issue outlined in #66. For Webpacker users, Stimulus is still published on NPM under `"stimulus"` and so we need to remove the `@hotwired/` prefix from the package name for now.

Rename Stimulus NPM package in hello controller for Webpacker users

---

lib/install/stimulus_with_asset_pipeline.rb

When `APP_JS_PATH` doesn't exist instructions are displayed by the install script. These contained `import @hotwire/...` instead of `import @hotwired/...`

Update install instructions with proper `hotwired` import

---

app/assets/javascripts/stimulus-importmap-autoloader.js

While transitioning a project from `webpacker` to `importmap-rails` I discovered a handful of my controllers weren't connecting. The root of the problem is that filenames are being transformed into registered controller names differently across `stimulus-autoloader` and `stimulus-importmap-autoloader`. This impacts controllers that have three or more words in their name.
```
/app/assets/javascripts/controllers/many_much_words_controller.js
many-much_words
many-much-words
```
This change makes it so that `stimulus-autoloader` and `stimulus-importmap-autoloader` consistently transform the filename, easing the transition for any other applications that might have a `really_long_and_descriptive_controller.js`.

🍡 Consitently kebab-case controller names in autoloaders

---

app/assets/javascripts/stimulus-importmap-autoloader.js

Currently, with sidecar view_components, the `HelloWorldComponent` will get a name of `hello-world-componenthello-world-component`. With this change, the resulting name will be `hello-world-component`.
This means we can now do
```
registerControllerFrom(".*_component", application)
```
to load all the stimulus controllers that I define for any view components.

Handle controller naming for view_components

---

lib/generators/stimulus/stimulus_generator.rb
test/generator_test.rb

The stimulus generator expects a much more restrictive naming convention compared to other rails-esqe generators such as `model` or `controller`.
When developing, I found myself copying strings from the ERB templates and pasting them into the command-line to generate a stimulus controller (like `rails generate stimulus hello-world`). Currently, the generator generates incorrect file names and data-attribute comments. In my example, the generator would create a `hello-world_controller.js` file. 
Today, this happened one too many times, so I created this PR. 
In essence, it uses `name.underscore` to normalize the controller name and then generates the appropriate data-attribute comment and file name. Additionally, it removes `_controller` suffixes from the name, which also got me several …

Improve Name Handling of Stimulus Generator

---

lib/generators/stimulus/stimulus_generator.rb

Only run stimulus:manifest:update if (seemingly) not using importmaps. Resolves #87

Check for importmap configuration before updating manifest

---

app/assets/javascripts/stimulus-loading.js

Partially reverts https://github.com/hotwired/stimulus-rails/commit/67e2cf3d419584628d7fe9b7857312ebd53d052e#diff-8e0a8f9875453f690405e8c037a8e76c4436f09f47fd9c605283c2f16bd95789L77
Resolves an issue where a controller is registered twice.
I created a sample Rails app to reproduce this issue. Relevant commit: https://github.com/lewispb/stimulus-loader-issue/commit/ce8aaa57a72473febd1b279847dc2fa33b859cee
To reproduce:
1. Insert a Turbo Stream element onto the page which in turn appends an element specifying a Stimulus controller
2. It appears the mutation observer triggers twice, once for the HTML element mutating (as the Turbo Stream element is inserted into the dom) and once for the append performed by the Turbo Stream action.
3. This triggers registering the Stimulus controller twice, …

Fix bug when mutation causes controller to be registered twice

---

app/assets/javascripts/stimulus-loading.js

Fixes issue https://github.com/hotwired/stimulus-rails/issues/111 where lazy loading will attempt to load the external stimulus controller even if it was registered manually. 
Improves on the fix from https://github.com/hotwired/stimulus-rails/pull/97 where a new lookup table is created to check if a controller is registered or not. Stimulus already maintains this mapping [here](https://github.com/hotwired/stimulus-rails/blob/ef2f33d0af802461d9cc431ac5888b2461f71af2/app/assets/javascripts/stimulus.js#L1870) which we can use to determine if a controller was registered outside of `stimulus-loading`'s scope and avoid re-registering it.

Use stimulus router lookup table to decide if controller is registered

---

lib/generators/stimulus/stimulus_generator.rb

Some projects don't need to generate manifest (for example when using [stimulus-controller-resolver](https://github.com/danieldiekmeier/stimulus-controller-resolver)) when generating a new stimulus controller
Here is an option to skip it

Add skip_manifest option to generator

---

lib/install/stimulus_with_bun.rb
lib/tasks/stimulus_tasks.rake

This PR [is part of an overall effort ](https://github.com/rails/rails/pull/49241) to allow Rails developers to completely use the Bun JS runtime and bundler without needing to use Node.JS and Yarn.
This gem is automatically invoked when a new rails projects is created and before this PR would always use Yarn. After this PR this gem will detect which JS bundler is being used and use the correct one so that Yarn doesn't accidentally slip into your Rails project.
[I have opened a companion PR to the turbo-rails repo as well.](https://github.com/hotwired/turbo-rails/pull/494)
```
☁  test_app [main] ./bin/rails javascript:install:bun
Compile into app/assets/builds
create  app/assets/builds
create  app/assets/builds/.keep
append  app/assets/config/manifest.js
append  .gitignore
append …
```

Use bun for installation if applicable

---

lib/stimulus/manifest.rb
test/fixtures/controllers/hello_controller.ts
test/manifest_test.rb

Fixes https://github.com/hotwired/stimulus/issues/739
when typescript and js controllers are named the same. For example, `hello_controller.js` and `hello_controller.ts` and placed in the controllers folder, `index.js` is updated with duplicate content to register the controllers.
```js
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { application } from "./application"
import HelloController from "./hello_controller"
application.register("hello", HelloController)
import HelloController from "./hello_controller"
application.register("hello", HelloController)
```

fix duplicate controllers in manifest on update

---

lib/tasks/stimulus_tasks.rake

Describe the two options under stimulus:manifest so they can be found in a `rails -T` listing.

Update stimulus_tasks.rake (closes #128)

---

lib/install/stimulus_with_node.rb

Add support for bun
If you create a new rails project with "--main --javascript bun"
you end up with a yarn.lock and not a bun.lockb file.  This is
because turbo-rails and stimuls are installed with yarn.

Bun support

---

lib/stimulus/manifest.rb
test/fixtures/controllers/multi-word-dash_controller.js
test/fixtures/controllers/multi_word_underscore_controller.js
test/fixtures/controllers/namespace/multi-word-dash_controller.js
test/fixtures/controllers/namespace/multi_word_underscore_controller.js
test/fixtures/controllers/namespace/namespaced_controller.js
test/manifest_test.rb

This PR extends the current functionality of the Gem to support Stimulus controllers with dasherized names (`multi-word-dash_controller.js`), in addition to the existing camel_case support (`multi_word_controller.js`).
The Gem currently supports only Stimulus controllers with names in camel_case.
Dasherized names is part of the Stimulus documentation https://stimulus.hotwired.dev/reference/controllers#identifiers
Given that the controller name written in the DOM is using dash to me it feels more natural to write it like that in my filename.
This PR adds support for dasherized controller names and includes a corresponding test case. With these changes, the Gem will support the following naming structures:
```
├── coffee_controller.coffee
├── hello_controller.js
├── …
```

Support for dasherized controller filenames

---

lib/install/stimulus_with_node.rb

Fix syntax error:
```
$ rails stimulus:install
gems/stimulus-rails-1.3.2/lib/install/stimulus_with_node.rb:18: syntax error, unexpected ')', expecting `then' or ';' or '\n' (SyntaxError)
...ils.root.join("bun.config.js")).exist?
```
Which introduced in #127

Fix syntax error in stimulus_with_node.rb

---

README.md

If I use ```import controllers``` as mentioned in the README I get the following error:
```
13:15:21 js.1   |   errors: [
13:15:21 js.1   |     {
13:15:21 js.1   |       detail: undefined,
13:15:21 js.1   |       id: '',
13:15:21 js.1   |       location: {
13:15:21 js.1   |         column: 7,
13:15:21 js.1   |         file: 'application.js',
13:15:21 js.1   |         length: 13,
13:15:21 js.1   |         line: 24,
13:15:21 js.1   |         lineText: 'import "controllers";',
13:15:21 js.1   |         namespace: '',
13:15:21 js.1   |         suggestion: '"./controllers"'
13:15:21 js.1   |       },
13:15:21 js.1   |       notes: [
13:15:21 js.1   |         {
13:15:21 js.1   |           location: null,
13:15:21 js.1   |           text: 'Use the relative path "./controllers" to reference the …
```

Fixed example in the readme

---

lib/install/app/javascript/controllers/index_for_importmap.js

It causes timing issues and is not desirable for the vast majority of applications.

Stop suggesting lazy loading

---

lib/tasks/stimulus_tasks.rake

This is a very small fix to the installation process. In run_stimulus_install_template the path may contain a space. In my case, the bundle directory has a space in it for some reason unknown to me (vendor/bundle /). In the old code this broke the system call and prevented generation of a new rails project by rails new app_name. The new version is in line with other library install templates like importmap)
I'm using rbenv on Arch, ruby 3.3.1, rails 7.1.3.2.

Changed install template system call to account for spaces in path

---

stimulus-rails.gemspec

By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/stimulus-rails which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/

Provide a 'Changelog' link on rubygems.org/gems/stimulus-rails

---

app/assets/javascripts/stimulus-loading.js

Fixes https://github.com/hotwired/stimulus-rails/issues/102
When failing to register a controller, Stimulus catches the error and logs a console message. But that means the error won't be logged in a monitoring tool, making it hard to identify the issue.
This change follows the pattern in other files to catch this Type Error, format an error message, and re-throw the error so it can be tracked by monitoring tools.
This is my first contribution to Stimulus, so please let me know what I am missing. Thanks for reviewing it!
PS. I noticed we don't have unit JS tests. Would setting something up for unit tests be a helpful future contribution?

Rethrow error when failing to register a controller
